/* ===========================================================================
 * BASIS PENGETAHUAN CHATBOT — HUTAN INTERNET
 * ===========================================================================
 * File ini adalah SATU-SATUNYA sumber isi chatbot.
 * Chatbot hanya boleh menjawab berdasarkan entri di sini.
 *
 * Untuk memperbarui materi: edit `contentId` / `contentEn` di entri yang
 * sesuai, atau tambah entri baru mengikuti pola yang sama.
 *
 * Field:
 *   id          — kode KB, dipakai sebagai referensi internal
 *   titleId     — judul ringkas (Bahasa Indonesia)
 *   titleEn     — judul ringkas (English)
 *   contentId   — teks materi (Bahasa Indonesia)
 *   contentEn   — teks materi (English)
 *   keywords    — array kata kunci (huruf kecil) untuk pencocokan query
 *   sourceLabelId — label sumber yang ditampilkan ke pengguna (Indonesia)
 *   sourceLabelEn — label sumber yang ditampilkan ke pengguna (English)
 * ======================================================================== */

export const knowledgeBase = [
  {
    id: 'KB-00',
    titleId: 'Identitas dan Tujuan Pembelajaran',
    titleEn: 'Identity and Learning Objectives',
    contentId:
      '🌲 Materi ini berjudul "Petualangan Arif & Safira di Hutan Internet". Materi mengajarkan cara belajar aman, baik, dan pintar saat memakai internet. Sasaran utamanya adalah siswa SD kelas 4–6, tetapi guru dan orang tua juga dapat memanfaatkannya.\n\nJurus utama saat menggunakan internet adalah: Berhenti, Cek, Cerita 🛑.\n\n• 🛑 Berhenti: jangan langsung memberikan data, memercayai kabar, membagikan sesuatu, atau membalas saat sedang marah.\n• 🔍 Cek: periksa kembali apa yang terlihat, sumber kabar, serta apakah informasi pribadi ikut tersebar.\n• 🗣️ Cerita: minta bantuan dan ceritakan kepada orang dewasa yang dipercaya ketika ragu, takut, bingung, atau merasa tidak aman.',
    contentEn:
      '🌲 This material is called "Arif & Safira\'s Adventure in the Internet Forest". It teaches children how to stay safe, be kind, and be smart when using the internet. The main audience is primary school students in grades 4–6, but teachers and parents can also benefit from it.\n\nThe three key moves when using the internet are: Stop, Check, Tell 🛑.\n\n• 🛑 Stop: do not immediately share data, trust news, forward things, or reply when angry.\n• 🔍 Check: review what you see, the source of the news, and whether any personal information is being exposed.\n• 🗣️ Tell: ask for help and tell a trusted adult when you feel unsure, afraid, confused, or unsafe.',
    keywords: [
      'hutan internet',
      'arif',
      'safira',
      'piko',
      'tujuan',
      'materi',
      'belajar',
      'aman',
      'baik',
      'pintar',
      'berhenti',
      'cek',
      'cerita',
      'stop',
      'check',
      'tell',
      'jurus',
      'internet forest',
      'learning',
      'safe',
      'petualangan',
      'adventure',
      'sd',
      'primary school',
      'guru',
      'orang tua',
      'teacher',
      'parent',
    ],
    sourceLabelId: 'Materi Utama — Hutan Internet',
    sourceLabelEn: 'Main Material — Internet Forest',
  },
  {
    id: 'KB-01',
    titleId: 'Internet Seperti Hutan',
    titleEn: 'The Internet is Like a Forest',
    contentId:
      '🌲 Internet dapat diibaratkan seperti hutan. Di internet ada banyak tempat untuk belajar dan bermain — teman baik, video seru, dan game menarik ✨. Namun ada juga jalan yang perlu dilewati dengan hati-hati.\n\nKarena itu, kita membutuhkan "peta aman" saat menjelajahi internet 🗺️. Sama seperti di hutan, kita perlu tahu ke mana harus pergi dan apa yang perlu diwaspadai.',
    contentEn:
      "🌲 The internet can be compared to a forest. There are many places to learn and play — good friends, fun videos, and exciting games ✨. But there are also paths that need to be walked carefully.\n\nThat is why we need a 'safety map' when exploring the internet 🗺️. Just like in a forest, we need to know where to go and what to watch out for.",
    keywords: [
      'hutan',
      'internet',
      'forest',
      'aman',
      'safe',
      'peta',
      'map',
      'jelajahi',
      'explore',
      'hati-hati',
      'careful',
      'belajar',
      'learn',
      'bermain',
      'play',
      'teman',
      'friend',
      'video',
      'game',
      'jalan',
      'path',
      'waspada',
    ],
    sourceLabelId: 'Bekal Pengantar — Internet Seperti Hutan',
    sourceLabelEn: 'Introduction — The Internet is Like a Forest',
  },
  {
    id: 'KB-02',
    titleId: 'Bekal 1: Jaga Rahasia Dirimu',
    titleEn: 'Tip 1: Protect Your Personal Data',
    contentId:
      '🔒 Data pribadi adalah rahasia penting yang harus dijaga. Jangan memberikan nama lengkap, alamat rumah, nama sekolah, atau kelas kepada orang yang baru dikenal di internet 🛡️.\n\nHadiah, top up, atau gift bukan alasan untuk memberikan data pribadi 🎮. Kalau ada orang yang meminta data tersebut, katakan tidak dan ceritakan kepada orang dewasa yang kamu percaya.',
    contentEn:
      '🔒 Personal data is an important secret that must be protected. Do not share your full name, home address, school name, or class with people you have just met online 🛡️.\n\nA gift, top-up, or prize is never a good reason to share personal data 🎮. If someone asks for that information, say no and tell a trusted adult.',
    keywords: [
      'data pribadi',
      'personal data',
      'nama',
      'name',
      'alamat',
      'address',
      'sekolah',
      'school',
      'kelas',
      'class',
      'rahasia',
      'secret',
      'hadiah',
      'gift',
      'top up',
      'topup',
      'reward',
      'jaga',
      'protect',
      'orang baru',
      'stranger',
      'jangan kasih',
      'tidak boleh',
      'dont share',
      'privasi',
      'privacy',
      'identitas',
      'identity',
      'nomor telepon',
      'phone number',
    ],
    sourceLabelId: 'Bekal 1 — Jaga Rahasia Dirimu',
    sourceLabelEn: 'Tip 1 — Protect Your Personal Data',
  },
  {
    id: 'KB-03',
    titleId: 'Bekal 2: Pikir Dulu Sebelum Posting',
    titleEn: 'Tip 2: Think Before You Post',
    contentId:
      '📸 Saat melakukan live, bermain game, atau mengunggah foto/video, perhatikan semua hal yang ikut terlihat. Jangan sampai alamat rumah, sekolah, nomor telepon, atau lokasi ikut tersebar tanpa sengaja 📍.\n\nKalau ragu tentang apa yang akan diposting, tanyakan kepada orang tua atau guru terlebih dahulu sebelum menekan tombol posting ✨.',
    contentEn:
      '📸 When going live, playing games, or uploading photos or videos, pay attention to everything that might be visible in the background. Make sure your home address, school, phone number, or location do not accidentally get shared 📍.\n\nIf you are unsure about what you are about to post, ask a parent or teacher first before pressing the post button ✨.',
    keywords: [
      'posting',
      'post',
      'upload',
      'foto',
      'photo',
      'video',
      'live',
      'game',
      'lokasi',
      'location',
      'pikir dulu',
      'think before',
      'latar belakang',
      'background',
      'tersebar',
      'spread',
      'media sosial',
      'social media',
      'unggah',
      'share',
      'bagikan',
      'konten',
      'content',
      'privat',
      'private',
      'aman posting',
      'safe posting',
    ],
    sourceLabelId: 'Bekal 2 — Pikir Dulu Sebelum Posting',
    sourceLabelEn: 'Tip 2 — Think Before You Post',
  },
  {
    id: 'KB-04',
    titleId: 'Bekal 3: Jaga Passwordmu',
    titleEn: 'Tip 3: Protect Your Password',
    contentId:
      '🔑 Password adalah kunci rumah digitalmu. Jangan memberikan password kepada siapa pun, termasuk teman dekat atau sahabatmu 🚪. Jangan juga menggunakan password yang mudah ditebak seperti tanggal lahir atau nama sendiri.\n\nKalau bingung tentang akun, minta bantuan orang tua atau guru — jangan coba mengatasinya sendiri dengan memberikan password ke orang lain 🧑‍🏫.',
    contentEn:
      "🔑 A password is the key to your digital home. Never give your password to anyone, including close friends or best friends 🚪. Also avoid using passwords that are easy to guess, like your birthday or your own name.\n\nIf you are confused about an account, ask a parent or teacher for help — do not try to fix it yourself by sharing your password with someone else 🧑‍🏫.",
    keywords: [
      'password',
      'kata sandi',
      'sandi',
      'kunci',
      'key',
      'akun',
      'account',
      'kasih password',
      'share password',
      'teman',
      'friend',
      'sahabat',
      'best friend',
      'mudah ditebak',
      'easy to guess',
      'tanggal lahir',
      'birthday',
      'nama sendiri',
      'own name',
      'digital',
      'keamanan akun',
      'account security',
      'lupa password',
      'forgot password',
    ],
    sourceLabelId: 'Bekal 3 — Jaga Passwordmu',
    sourceLabelEn: 'Tip 3 — Protect Your Password',
  },
  {
    id: 'KB-05',
    titleId: 'Bekal 4: Cek Dulu Kabarnya',
    titleEn: 'Tip 4: Check the News First',
    contentId:
      '📰 Pesan seperti "besok sekolah libur" atau judul berita yang heboh belum tentu benar. Sebelum percaya dan menyebarkan, periksa dulu kabarnya kepada guru, orang tua, grup resmi sekolah, atau sumber yang jelas 🔍.\n\nJangan langsung membagikan kabar hanya karena sedang ramai atau banyak yang berbagi. Prinsip utamanya: cek dulu sebelum percaya dan menyebarkan ✨.',
    contentEn:
      '📰 Messages like "no school tomorrow" or sensational news headlines may not be true. Before believing and sharing something, check it with a teacher, parent, the official school group, or a clear source 🔍.\n\nDo not immediately share news just because it is trending or many people are sharing it. The key principle is: check first before you believe and forward anything ✨.',
    keywords: [
      'kabar',
      'news',
      'berita',
      'cek',
      'check',
      'libur',
      'holiday',
      'hoaks',
      'hoax',
      'disinformasi',
      'misinformasi',
      'misinformation',
      'disinformation',
      'besok libur',
      'pesan',
      'message',
      'share',
      'bagikan',
      'forward',
      'sebarkan',
      'ramai',
      'trending',
      'viral',
      'benar',
      'true',
      'palsu',
      'fake',
      'sumber',
      'source',
      'grup resmi',
      'official group',
      'verifikasi',
      'verify',
    ],
    sourceLabelId: 'Bekal 4 — Cek Dulu Kabarnya',
    sourceLabelEn: 'Tip 4 — Check the News First',
  },
  {
    id: 'KB-06',
    titleId: 'Bekal 5: Hati-Hati dengan Gambar dan Video AI',
    titleEn: 'Tip 5: Beware of AI Images and Videos',
    contentId:
      '🖼️ Foto yang terlihat sangat nyata belum tentu benar. Suara dan video juga dapat dibuat atau diubah menggunakan AI (kecerdasan buatan), sehingga terlihat dan terdengar asli padahal sebenarnya tidak 🤖.\n\nKalau melihat atau mendengar sesuatu yang terasa aneh, jangan langsung percaya. Mata kita hebat, tetapi kita tetap perlu melakukan pengecekan kepada orang dewasa atau sumber yang dapat dipercaya 🔍.',
    contentEn:
      '🖼️ A photo that looks very real may not actually be true. Sound and video can also be created or altered using AI (artificial intelligence), making them look and sound authentic even though they are not 🤖.\n\nIf you see or hear something that feels strange or too good to be true, do not believe it right away. Our eyes are amazing, but we still need to check with a trusted adult or reliable source 🔍.',
    keywords: [
      'ai',
      'artificial intelligence',
      'kecerdasan buatan',
      'gambar',
      'image',
      'foto',
      'photo',
      'video',
      'suara',
      'sound',
      'audio',
      'deepfake',
      'palsu',
      'fake',
      'nyata',
      'real',
      'asli',
      'authentic',
      'diubah',
      'edited',
      'manipulasi',
      'manipulation',
      'terlihat nyata',
      'looks real',
      'pasti benar',
      'must be true',
      'aneh',
      'strange',
      'hati-hati',
      'careful',
      'teknologi',
      'technology',
    ],
    sourceLabelId: 'Bekal 5 — Hati-Hati dengan Gambar dan Video AI',
    sourceLabelEn: 'Tip 5 — Beware of AI Images and Videos',
  },
  {
    id: 'KB-07',
    titleId: 'Bekal 6: Jadi Teman yang Baik',
    titleEn: 'Tip 6: Be a Good Friend',
    contentId:
      '🤝 Jangan ikut menyebarkan foto yang digunakan untuk mengejek atau mempermalukan teman. Kalau sedang marah, jangan menulis ejekan atau kata-kata menyakitkan di internet — tulisan dan komentar di internet tetap dapat menyakiti perasaan orang, sama seperti kata-kata langsung 💬.\n\nKalau ada teman yang mengalami hal tidak menyenangkan di internet, hibur dia dan ceritakan kepada guru atau orang tua. Kamu bisa menjadi teman yang baik dengan tidak ikut-ikutan dan dengan melaporkan situasi itu kepada orang dewasa 💛.',
    contentEn:
      '🤝 Do not share photos that are being used to mock or embarrass a friend. If you are angry, do not write hurtful comments online — words and comments on the internet can hurt just as much as words spoken face to face 💬.\n\nIf a friend is experiencing something unpleasant online, comfort them and tell a teacher or parent. You can be a good friend by not joining in and by reporting the situation to a trusted adult 💛.',
    keywords: [
      'teman',
      'friend',
      'baik',
      'good',
      'bully',
      'bullying',
      'ejek',
      'mock',
      'menyakiti',
      'hurt',
      'kata-kata',
      'words',
      'komentar',
      'comment',
      'foto ejek',
      'mocking photo',
      'sebarkan foto',
      'share photo',
      'marah',
      'angry',
      'pertemanan',
      'friendship',
      'siber',
      'cyber',
      'cyberbullying',
      'online',
      'hibur',
      'comfort',
      'laporkan',
      'report',
      'mempermalukan',
      'humiliate',
      'diejek',
      'temanku diejek',
    ],
    sourceLabelId: 'Bekal 6 — Jadi Teman yang Baik',
    sourceLabelEn: 'Tip 6 — Be a Good Friend',
  },
  {
    id: 'KB-08',
    titleId: 'Bekal 7: Cari Bantuan Kalau Takut',
    titleEn: 'Tip 7: Seek Help If You Feel Scared',
    contentId:
      '🚨 Kalau kamu menerima pesan yang menakutkan atau diganggu oleh sebuah akun di internet, ada tiga langkah yang perlu dilakukan:\n\n1. 📸 Simpan bukti — screenshot atau simpan pesan yang menakutkan itu.\n2. 🚫 Blokir akun yang mengganggu supaya dia tidak bisa menghubungimu lagi.\n3. 🗣️ Ceritakan kepada orang dewasa yang kamu percaya, seperti orang tua, guru, atau anggota keluarga dewasa lainnya.\n\nIngat: kamu tidak harus menghadapi situasi itu sendirian. Selalu ada orang dewasa yang siap membantu 🛡️.',
    contentEn:
      '🚨 If you receive a scary message or are being bothered by an account online, there are three steps to take:\n\n1. 📸 Save the evidence — take a screenshot or save the scary message.\n2. 🚫 Block the account that is bothering you so they cannot contact you again.\n3. 🗣️ Tell a trusted adult, such as a parent, teacher, or another adult family member.\n\nRemember: you do not have to face this situation alone. There is always a trusted adult ready to help 🛡️.',
    keywords: [
      'takut',
      'scared',
      'afraid',
      'ganggu',
      'bother',
      'harass',
      'pesan menakutkan',
      'scary message',
      'ancaman',
      'threat',
      'akun',
      'account',
      'blokir',
      'block',
      'bukti',
      'evidence',
      'screenshot',
      'simpan bukti',
      'save evidence',
      'bantuan',
      'help',
      'cari bantuan',
      'seek help',
      'orang dewasa',
      'adult',
      'ceritakan',
      'tell',
      'tidak sendirian',
      'not alone',
      'aman',
      'safe',
      'dilaporkan',
      'report',
      'diganggu',
      'dibully',
      'mengancam',
    ],
    sourceLabelId: 'Bekal 7 — Cari Bantuan Kalau Takut',
    sourceLabelEn: 'Tip 7 — Seek Help If You Feel Scared',
  },
  {
    id: 'KB-09',
    titleId: 'Ringkasan Lima Hal Penting',
    titleEn: 'Summary: Five Key Things to Remember',
    contentId:
      '✨ Ada lima hal penting yang perlu selalu diingat saat menggunakan internet:\n\n1. 🔒 Jaga data pribadi — jangan bagikan nama lengkap, alamat, sekolah, atau kelas kepada orang yang baru dikenal.\n2. 🔑 Jaga password — jangan berikan kepada siapa pun, termasuk teman.\n3. 🔍 Cek sebelum percaya — periksa dulu kabar atau berita sebelum menyebarkannya.\n4. 🤝 Jangan mengejek — kata-kata di internet juga bisa menyakiti.\n5. 🛡️ Cari bantuan jika merasa tidak aman — simpan bukti, blokir, dan cerita kepada orang dewasa.',
    contentEn:
      '✨ There are five important things to always remember when using the internet:\n\n1. 🔒 Protect your personal data — do not share your full name, address, school, or class with strangers.\n2. 🔑 Protect your password — do not give it to anyone, including friends.\n3. 🔍 Check before you believe — verify news or information before sharing it.\n4. 🤝 Do not mock others — words on the internet can still cause pain.\n5. 🛡️ Seek help if you feel unsafe — save evidence, block the account, and tell a trusted adult.',
    keywords: [
      'ringkasan',
      'summary',
      'recap',
      'lima',
      'five',
      'hal penting',
      'key things',
      'tips',
      'ingat',
      'remember',
      'semua',
      'all',
      'daftar',
      'list',
      'penting',
      'important',
      'intinya',
      'kesimpulan',
      'conclusion',
      'pelajaran',
      'lesson',
    ],
    sourceLabelId: 'Ringkasan — Lima Hal Penting',
    sourceLabelEn: 'Summary — Five Key Things',
  },
  {
    id: 'KB-10',
    titleId: 'Pesan Penutup',
    titleEn: 'Closing Message',
    contentId:
      '🦉 Anak yang sudah mempelajari materi Hutan Internet ini telah belajar menggunakan internet dengan aman dan baik. Selamat, kamu kini menjadi Penjaga Hutan Internet yang pintar dan baik! ✨\n\nJurus utama yang selalu perlu diingat adalah: Berhenti, Cek, Cerita 🛑. Gunakan tiga jurus ini setiap kali menghadapi situasi yang tidak pasti di internet.',
    contentEn:
      '🦉 Children who have studied the Internet Forest material have learned how to use the internet safely and responsibly. Congratulations — you are now a smart and kind Guardian of the Internet Forest! ✨\n\nThe three key moves to always remember are: Stop, Check, Tell 🛑. Use these three moves every time you face an uncertain situation online.',
    keywords: [
      'penjaga',
      'guardian',
      'selamat',
      'congratulations',
      'selesai',
      'done',
      'penutup',
      'closing',
      'berhenti cek cerita',
      'stop check tell',
      'ingat',
      'remember',
      'pintar',
      'smart',
      'baik',
      'kind',
      'lulus',
      'graduate',
      'berhasil',
      'succeed',
    ],
    sourceLabelId: 'Pesan Penutup — Penjaga Hutan Internet',
    sourceLabelEn: 'Closing Message — Guardian of the Internet Forest',
  },
]

/**
 * Fallback resmi yang wajib digunakan bila tidak ada entri yang cukup relevan.
 * Selalu sertakan emotikon ramah.
 */
export const FALLBACK = {
  id: 'Maaf, informasi itu belum tersedia dalam materi pembelajaran Hutan Internet 🌲. Kamu bisa bertanya tentang data pribadi 🔒, password 🔑, mengecek kabar 🔍, gambar atau video AI 🤖, menjadi teman yang baik 🤝, atau mencari bantuan saat merasa tidak aman 🛡️.',
  en: 'Sorry, that information is not available in the Hutan Internet learning material yet 🌲. You can ask about personal data 🔒, passwords 🔑, checking information 🔍, AI images or videos 🤖, being a good friend 🤝, or getting help when you feel unsafe 🛡️.',
}
